version: '3'
services:
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ${ROOT_PROJECT_FOLDER}/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ${ROOT_PROJECT_FOLDER}/app:/app
  php:
    restart: unless-stopped
    volumes:
      - ${ROOT_PROJECT_FOLDER}/app:/app
    environment:
      - "LANG=en_US.utf8"
      - "XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}"
      - "XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT}"
    build:
      context: .
      dockerfile: PHP.Dockerfile
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'pyastolov'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'test'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-data: { }