version: '3'
services:
  web:
    container_name: "profiteer-nginx"
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "${PUBLIC_PORT}:80"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    volumes:
      - ${ROOT_PROJECT_FOLDER}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${ROOT_PROJECT_FOLDER}/app:/app
    networks:
      - app-network
  php:
    container_name: "php"
    restart: unless-stopped
    volumes:
      - ${ROOT_PROJECT_FOLDER}/app:/app
    environment:
      - "LANG=en_US.utf8"
      - "XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}"
      - "XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT}"
    build:
      context: .
      dockerfile: PHP.Dockerfile
    dns:
      - 8.8.8.8
      - 4.4.4.4
    networks:
      - app-network
  mysql:
    container_name: "profiteer-mysql"
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'pyastolov'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'test'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
volumes:
  mysql-data: { }
#Docker Networks
networks:
  app-network:
    driver: bridge